### ISSUE TITLE
google chromium causes kernel panic on Haswell

### ISSUE THREAD

**Issue by nomadlogic** [FreeBSDDesktop/freebsd-base-graphics#13]
hw.model: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz

$ uname -a
FreeBSD beastie.mydomain.local 11.0-ALPHA1 FreeBSD 11.0-ALPHA1 #0 aa431a3(drm-next-4.6): Tue May 31 21:54:56 UTC 2016     root@beastie.mydomain.local:/usr/obj/mnt/sys/GENERIC  amd64

Start X with SNA enabled using cwm as my window manager.  i then start xterm and from there launch google chromium.  This results in a kernel panic with the following backtrace.  Looks like I need to rebuild my kernel with optimization flags disabled but hopefully this is helpful.

```
Fatal trap 12: page fault while in kernel mode
cpuid = 3; apic id = 03
fault virtual address   = 0x3c0
fault code              = supervisor read data, page not present
instruction pointer     = 0x20:0xffffffff82e7ecaa
stack pointer           = 0x28:0xfffffe046294e6a0
frame pointer           = 0x28:0xfffffe046294e750
code segment            = base 0x0, limit 0xfffff, type 0x1b
                        = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags        = interrupt enabled, resume, IOPL = 0
current process         = 0 (i915-hangcheck)

<snip>

(kgdb) bt
#0  doadump (textdump=1) at pcpu.h:221
#1  0xffffffff80a462b5 in kern_reboot (howto=<value optimized out>) at /mnt/sys/kern/kern_shutdown.c:366
#2  0xffffffff80a4688b in vpanic (fmt=<value optimized out>, ap=<value optimized out>) at /mnt/sys/kern/kern_shutdown.c:767
#3  0xffffffff80a468d3 in panic (fmt=0x0) at /mnt/sys/kern/kern_shutdown.c:690
#4  0xffffffff80a50251 in mi_switch (flags=<value optimized out>, newtd=<value optimized out>) at /mnt/sys/kern/kern_synch.c:389
#5  0xffffffff80a93d96 in sleepq_switch (wchan=<value optimized out>, pri=0) at /mnt/sys/kern/subr_sleepqueue.c:557
#6  0xffffffff80a94373 in sleepq_timedwait (wchan=0xfffffe046294e930, pri=0) at /mnt/sys/kern/subr_sleepqueue.c:672
#7  0xffffffff80a4fa18 in _sleep (ident=0xfffffe046294e930, lock=<value optimized out>, priority=<value optimized out>, wmesg=<value optimized out>, 
    sbt=214748350, pr=0, flags=<value optimized out>) at /mnt/sys/kern/kern_synch.c:225
#8  0xffffffff82fefabf in schedule_timeout (timeout=<value optimized out>) at /mnt/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:214
#9  0xffffffff82ea98e8 in intel_atomic_commit (dev=<value optimized out>, state=<value optimized out>, async=<value optimized out>)
    at /mnt/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/intel_display.c:13439
#10 0xffffffff82f9471c in drm_fb_helper_restore_fbdev_mode_unlocked (fb_helper=<value optimized out>)
    at /mnt/sys/modules/drm2/drm2/../../../dev/drm2/drm_fb_helper.c:383
#11 0xffffffff82facc49 in vt_kms_postswitch (arg=0xfffff80005245d40) at /mnt/sys/modules/drm2/drm2/../../../dev/drm2/linux_fb.c:76
#12 0xffffffff808d636b in vt_window_switch (vw=0xffffffff818ce250) at /mnt/sys/dev/vt/vt_core.c:540
#13 0xffffffff808d3e60 in vtterm_cngrab (tm=<value optimized out>) at /mnt/sys/dev/vt/vt_core.c:1465
#14 0xffffffff809eb5e2 in cngrab () at /mnt/sys/kern/kern_cons.c:368
#15 0xffffffff80a86e79 in kdb_trap (type=<value optimized out>, code=<value optimized out>, tf=<value optimized out>) at /mnt/sys/kern/subr_kdb.c:651
#16 0xffffffff80eb53f1 in trap_fatal (frame=0xfffffe046294e5f0, eva=960) at /mnt/sys/amd64/amd64/trap.c:836
#17 0xffffffff80eb563d in trap_pfault (frame=0xfffffe046294e5f0, usermode=0) at /mnt/sys/amd64/amd64/trap.c:691
#18 0xffffffff80eb4b24 in trap (frame=0xfffffe046294e5f0) at /mnt/sys/amd64/amd64/trap.c:442
#19 0xffffffff80e94fd1 in calltrap () at /mnt/sys/amd64/amd64/exception.S:236
#20 0xffffffff82e7ecaa in i915_capture_error_state (dev=<value optimized out>, wedged=Unhandled dwarf expression opcode 0x9d
) at pid.h:21
#21 0xffffffff82e82eaf in i915_handle_error (dev=0xfffff8005ab4b000, wedged=Unhandled dwarf expression opcode 0x9d
) at /mnt/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_irq.c:2674
#22 0xffffffff82e85344 in i915_hangcheck_elapsed (work=<value optimized out>) at /mnt/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_irq.c:3199
#23 0xffffffff82ff1e24 in linux_work_fn (context=0xfffffe0008a53188, pending=<value optimized out>)
    at /mnt/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:1466
#24 0xffffffff80a985fc in taskqueue_run_locked (queue=<value optimized out>) at /mnt/sys/kern/subr_taskqueue.c:463
#25 0xffffffff80a99148 in taskqueue_thread_loop (arg=<value optimized out>) at /mnt/sys/kern/subr_taskqueue.c:717
#26 0xffffffff80a090c4 in fork_exit (callout=0xffffffff80a990c0 <taskqueue_thread_loop>, arg=0xfffff8005aaeaf10, frame=0xfffffe046294eac0)
    at /mnt/sys/kern/kern_fork.c:1034
#27 0xffffffff80e9550e in fork_trampoline () at /mnt/sys/amd64/amd64/exception.S:611
#28 0x0000000000000000 in ?? ()
Current language:  auto; currently minimal
```

**Comment by nomadlogic** [comment]
closing this issue as it seems related to https://github.com/FreeBSDDesktop/freebsd-base-graphics/issues/2
