### ISSUE TITLE
6d310b5(drm-next-4.6) & xf86-video-intel-2.99.917.20160417 panic

### ISSUE THREAD

**Issue by nomadlogic** [FreeBSDDesktop/freebsd-base-graphics#18]
$ uname -ar
FreeBSD boomer 11.0-ALPHA1 FreeBSD 11.0-ALPHA1 #7 6d310b5(drm-next-4.6)-dirty: Sun Jun  5 20:01:31 PDT 2016     root@boomer:/usr/obj/usr/home/pwright/git/freebsd-base-graphics/sys/GENERIC  amd64
$ pkg info|grep intel
xf86-video-intel-2.99.917.20160417 Driver for Intel integrated graphics chipsets

When Xorg is configured to use SNA I get a hard crash requiring manual reboot.  Reverting Xorg to UXA works, but there are artifacts in x-windows.  i was able to capture a backtrace:

```
(kgdb) bt
#0  doadump (textdump=0) at pcpu.h:221
#1  0xffffffff82bfaf52 in drm_ut_debug_printk (function_name=0x0, format=0xffffffff82c3c71e "Set [NOFB] for plane state %p\n") at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/drm_drv.c:97
#2  0xffffffff82be08b1 in __drm_atomic_helper_disable_plane (plane=<value optimized out>, plane_state=0xfffff80008d60c00)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/drm_atomic_helper.c:1758
#3  0xffffffff82c037ce in drm_fb_helper_restore_fbdev_mode_unlocked (fb_helper=<value optimized out>) at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/drm_fb_helper.c:370
#4  0xffffffff82c1c039 in vt_kms_postswitch (arg=0xfffff80008c14680) at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/linux_fb.c:76
#5  0xffffffff808d736b in vt_window_switch (vw=0xffffffff818d7f10) at /usr/home/pwright/git/freebsd-base-graphics/sys/dev/vt/vt_core.c:540
#6  0xffffffff808d4e60 in vtterm_cngrab (tm=<value optimized out>) at /usr/home/pwright/git/freebsd-base-graphics/sys/dev/vt/vt_core.c:1465
#7  0xffffffff809ece32 in cngrab () at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_cons.c:368
#8  0xffffffff80a48026 in vpanic (fmt=0xffffffff81430458 "vm_page_free: freeing PG_UNHOLDFREE page %p", ap=0xfffffe0230baf280) at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_shutdown.c:745
#9  0xffffffff80a47f16 in kassert_panic (fmt=<value optimized out>) at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_shutdown.c:649
#10 0xffffffff80d3a79b in vm_page_free_toq (m=0xfffff802639ee318) at /usr/home/pwright/git/freebsd-base-graphics/sys/vm/vm_page.c:2987
#11 0xffffffff82a509ce in __free_hot_cold_page (vm_page=0xfffff802639ee318) at gfp.h:108
#12 0xffffffff82a4f098 in i915_gem_userptr_put_pages (obj=0xfffff80100140d80) at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_gem_userptr.c:691
#13 0xffffffff82a1ac41 in i915_gem_object_put_pages (obj=0xfffff80100140d80) at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_gem.c:2283
#14 0xffffffff82a1ff8f in i915_gem_free_object (gem_obj=0xfffff80100140d80) at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_gem.c:4651
#15 0xffffffff82c0953f in drm_gem_object_unreference_unlocked (obj=<value optimized out>) at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/drm_gem.c:793
#16 0xffffffff82c08c8d in drm_gem_object_release_handle (id=<value optimized out>, ptr=0xfffff80100140d80, data=0xfffff80008d17000)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/drm_gem.c:265
#17 0xffffffff82c08bb7 in drm_gem_handle_delete (filp=0xfffff80008d17000, handle=18) at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/drm_gem.c:308
#18 0xffffffff82c0ac21 in drm_ioctl (filp=<value optimized out>, cmd=2148033545, arg=<value optimized out>) at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/drm_ioctl.c:766
#19 0xffffffff82c61f8e in linux_dev_ioctl (dev=<value optimized out>, cmd=2148033545, data=0x0, fflag=<value optimized out>, td=0xfffff80100386000)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:919
#20 0xffffffff8091d6c6 in devfs_ioctl_f (fp=0xfffff80008beb690, com=2148033545, data=0xfffffe0230baf7f0, cred=0xfffff80008d29900, td=0xfffff80100386000) at /usr/home/pwright/git/freebsd-base-graphics/sys/fs/devfs/devfs_vnops.c:815
#21 0xffffffff80aac666 in kern_ioctl (td=<value optimized out>, fd=<value optimized out>, com=<value optimized out>, data=<value optimized out>) at file.h:328
#22 0xffffffff80aac3b1 in sys_ioctl (td=<value optimized out>, uap=0xfffffe0230baf940) at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/sys_generic.c:743
#23 0xffffffff80eb7beb in amd64_syscall (td=0xfffff80100386000, traced=0) at subr_syscall.c:135
#24 0xffffffff80e9764b in Xfast_syscall () at /usr/home/pwright/git/freebsd-base-graphics/sys/amd64/amd64/exception.S:396
#25 0x00000008024fcc0a in ?? ()
Previous frame inner to this frame (corrupt stack?)
```

looks like a corrupt stack - d'oh.

**Comment by nomadlogic** [comment]
as per mmacy i updated my kernel to fd8cdb9.  initial results looked good in fvwm as i was able to enable SNA acceleration and corruption was gone as well.  although after opening chromium i experienced a hard crash.  no core was saved, i'll try to reproduce this tonight.

**Comment by mattmacy** [comment]
I'm pretty sure this is fixed. Could you confirm and close please?

**Comment by nomadlogic** [comment]
can't reproduce crash from earlier so closing this guy out.
