### ISSUE TITLE
Artifact when starting X on Intel® HD Graphics 4400

### ISSUE THREAD

**Issue by nomadlogic** [FreeBSDDesktop/freebsd-base-graphics#2]
hw.model: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz

After loading the drm2 and i915kms kernel modules I generate an xorg.conf using "X  --configure".  This config allows me to start xfce4 but there are artifacts once xfce loads. Specifically there is no text in the login dialog.  Once I click on the dialog the system kernel panics at:

dev/drm2/drm_modeset_lock.c:336

I will post a backtrace and the Xorg once I have the system back online.

**Comment by nomadlogic** [comment]
quick update on this before i have to start my day-job.  i am able to launch kde4 and start xterm and konsole.  there is no text rendered in the xterm window at all.  i konsole the output is corrupt but usable for typing commands.

i ran glxgears and got ~50fps.  system kernel panic'd when i attempted to logout, once it recovers i'll attach the output from glxinfo as well as the Xorg.0.log file.  

i suspect the stack got corrupted when i panic'd but if it looks usable i'll also attach the backtrace.

**Comment by Juanitou** [comment]
I’m also getting visual artifacts with a 4400 (Haswell):
hw.model: Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz

I’m at the revision 34475b8ae1cd07d07e0e367296680157940f1307 and using cwm for testing. Pre-loading drm2 or i915kms is not required, but loading i915kms at boot time does not work yet.

The first xterm window opens split in two parts. Testing with long (> 30 min), fullscreen HD YouTube videos in vimb works pretty well. I can switch fullscreen on and off, move the window… but sometimes the thumbnail images of suggested videos get garbled (i.e. interlaced?) and the playing video itself can become garbled too. With older revisions this almost always lead to panic and reboot, but now it is really much more stable, but I have still had some panics that I cannot reproduce at will, always seemingly related to opening supplementary windows.

Hope it helps,
Juan

Edit: BTW, HDMI output is working and stable, tested while already running a video, changed mode, cloned, duplicated, etc. Cheers!

**Comment by mattmacy** [comment]
Can you post a picture of the screen when there are artifacts?

**Comment by mattmacy** [comment]
And are you using sna or uxa? I find the former works much better on haswell, whereas the latter will produce artifacts even at startup.

**Comment by Juanitou** [comment]
Hi Matthew and thanks again for your dedication. Here is what I have tested:

UXA was being picked by default. Here you have a screenshot of a video starting then the artifacts appearing after moving the pointer. These artifacts can also appear in the main video while playing. Soon after, putting the video on full screen then going to a window again crashed the system:
![Before artifact](http://atelierdelagrandesource.org/tmp/Before.jpg)
![After moving pointer](http://atelierdelagrandesource.org/tmp/After.jpg)

Then I switched over SNA. As a reference to other users, just this is needed in the `xorg.conf` file:

```
Section "Device"
        Identifier "Card0"
        Driver  "intel"
        Option  "AccelMethod" "SNA"
EndSection
```

With SNA, performance and stability improves to such a point that I have not been able to see a single artifact, nor crash the computer. I have had YouTube HD videos playing normal, then theater, then full screen then back again to window, etc. while changing the mode with xrandr and it has been snappy and very solid. If you have a specific test for me to do, don’t hesitate to ask.

Cheers!

**Comment by nomadlogic** [comment]
using the latest kernel from today

FreeBSD beastie.mydomain.local 11.0-ALPHA1 FreeBSD 11.0-ALPHA1 #0 aa431a3(drm-next-4.6): Tue May 31 21:54:56 UTC 2016     root@beastie.mydomain.local:/usr/obj/mnt/sys/GENERIC  amd64

I am still seeing a corrupted display using SNA acceleration.  this screenshot show's me launching cwm then starting firefox from an xterm.

![img_20160531_154930](https://cloud.githubusercontent.com/assets/8356819/15693168/0bc14636-2748-11e6-8959-e4320e7311b2.jpg)

Intel driver is configured like so:

```
 Section "Device"
        Option      "AccelMethod"               "sna"
        Identifier  "Card0"
        Driver      "intel"
        BusID       "PCI:0:2:0"
EndSection

```

**Comment by nomadlogic** [comment]
just tested this out again with the latest disk image "cftdisk_2016053119.img".  still getting artifacts, and triggered a kernel panic when attempting to resize xterm.  screenshot attached illustrating artifacts and resize attempt which triggered panic.

here is the kernel panic itself.

```
Unread portion of the kernel message buffer:
<6>[drm] stuck on render ring


Fatal trap 12: page fault while in kernel mode
cpuid = 2; apic id = 02
fault virtual address   = 0x3c0
fault code              = supervisor read data, page not present
instruction pointer     = 0x20:0xffffffff82e7fbca
stack pointer           = 0x28:0xfffffe046283b6a0
frame pointer           = 0x28:0xfffffe046283b750
code segment            = base 0x0, limit 0xfffff, type 0x1b
                        = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags        = interrupt enabled, resume, IOPL = 0
current process         = 0 (i915-hangcheck)

<snip>

(kgdb) #0  doadump (textdump=1) at pcpu.h:221
#1  0xffffffff80a462b5 in kern_reboot (howto=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/kern_shutdown.c:366
#2  0xffffffff80a4688b in vpanic (fmt=<value optimized out>, 
    ap=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/kern_shutdown.c:767
#3  0xffffffff80a468d3 in panic (fmt=0x0)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/kern_shutdown.c:690
#4  0xffffffff80a50251 in mi_switch (flags=<value optimized out>, 
    newtd=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/kern_synch.c:389
#5  0xffffffff80a93d96 in sleepq_switch (wchan=<value optimized out>, pri=0)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/subr_sleepqueue.c:557
#6  0xffffffff80a93c53 in sleepq_wait (wchan=0xfffff800346e1028, pri=0)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/subr_sleepqueue.c:637
#7  0xffffffff80a4ed50 in _sx_xlock_hard (sx=<value optimized out>, 
    tid=<value optimized out>, opts=<value optimized out>, 
    file=<value optimized out>, line=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/kern_sx.c:701
#8  0xffffffff80a4e1eb in _sx_xlock (sx=0xfffff800346e1028, opts=0, 
    file=0xffffffff83000fb7 "/usr/home/mmacy/devel/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_lock.c", line=38)
    at sx.h:154
#9  0xffffffff82ff854a in linux_mutex_lock_common (lock=0xfffff800346e1028, 
    state=<value optimized out>, ctx=0xfffff80034e1f0c0)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_lock.c:38
#10 0xffffffff82fa56a2 in modeset_lock (lock=0xfffff800346e1028, 
    ctx=0xfffff80034e1f0c0, interruptible=false, slow=true) at ww_mutex.h:66
#11 0xffffffff82fa4bb8 in drm_modeset_lock_all (dev=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/drm_modeset_lock.c:89
#12 0xffffffff82f945e4 in drm_fb_helper_restore_fbdev_mode_unlocked (
    fb_helper=0xfffff80010b19300)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/drm_fb_helper.c:468
#13 0xffffffff82facc49 in vt_kms_postswitch (arg=0xfffff80010110f40)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/linux_fb.c:76
#14 0xffffffff808d636b in vt_window_switch (vw=0xffffffff818d5e90)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/dev/vt/vt_core.c:540
#15 0xffffffff808d3e60 in vtterm_cngrab (tm=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/dev/vt/vt_core.c:1465
#16 0xffffffff809eb5e2 in cngrab ()
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/kern_cons.c:368
#17 0xffffffff80a86e79 in kdb_trap (type=<value optimized out>, 
    code=<value optimized out>, tf=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/subr_kdb.c:651
#18 0xffffffff80eb53f1 in trap_fatal (frame=0xfffffe046283b5f0, eva=960)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/amd64/amd64/trap.c:836
#19 0xffffffff80eb563d in trap_pfault (frame=0xfffffe046283b5f0, usermode=0)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/amd64/amd64/trap.c:691
#20 0xffffffff80eb4b24 in trap (frame=0xfffffe046283b5f0)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/amd64/amd64/trap.c:442
#21 0xffffffff80e94fd1 in calltrap ()
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/amd64/amd64/exception.S:236
#22 0xffffffff82e7fbca in i915_capture_error_state (
    dev=<value optimized out>, wedged=Unhandled dwarf expression opcode 0x9d
) at pid.h:21
#23 0xffffffff82e83d5f in i915_handle_error (dev=0xfffff800346c7000, wedged=Unhandled dwarf expression opcode 0x9d
)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_irq.c:2674
#24 0xffffffff82e861f4 in i915_hangcheck_elapsed (work=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_irq.c:3199
#25 0xffffffff82ff2e24 in linux_work_fn (context=0xfffffe000789b188, 
    pending=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:1466
#26 0xffffffff80a985fc in taskqueue_run_locked (queue=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/subr_taskqueue.c:463
#27 0xffffffff80a99148 in taskqueue_thread_loop (arg=<value optimized out>)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/subr_taskqueue.c:717
#28 0xffffffff80a090c4 in fork_exit (
    callout=0xffffffff80a990c0 <taskqueue_thread_loop>, 
    arg=0xfffff800342c0980, frame=0xfffffe046283bac0)
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/kern/kern_fork.c:1034
#29 0xffffffff80e9550e in fork_trampoline ()
    at /usr/home/mmacy/devel/freebsd-base-graphics/sys/amd64/amd64/exception.S:611
#30 0x0000000000000000 in ?? ()
Current language:  auto; currently minimal
(kgdb) 

```

![img_20160531_200540](https://cloud.githubusercontent.com/assets/8356819/15697293/a994851a-276d-11e6-9d4c-c183785fb814.jpg)

**Comment by mattmacy** [comment]
I can't see what's the potential problem in i915_capture_error_state. I need you to rebuild the driver with -O0 (add CFLAGS += -O0  to modules/drm2/i915/i915kms/Makefile) and reproduce.

**Comment by mattmacy** [comment]
The artifacts are because your render ring is hung. We need to track that down.

**Comment by nomadlogic** [comment]
OK rebuilt kernel with suggested modification and reproduced k.p. - let's see if this info helps:

```
Unread portion of the kernel message buffer:
<6>[drm] stuck on render ring


Fatal trap 12: page fault while in kernel mode
cpuid = 1; apic id = 01
fault virtual address   = 0x3c0
fault code              = supervisor read data, page not present
instruction pointer     = 0x20:0xffffffff82ea5ecb
stack pointer           = 0x28:0xfffffe046282c5c0
frame pointer           = 0x28:0xfffffe046282c5f0
code segment            = base 0x0, limit 0xfffff, type 0x1b
                        = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags        = interrupt enabled, resume, IOPL = 0
current process         = 0 (i915-hangcheck)

<snip>

Loaded symbols for /boot/kernel/linuxkpi.ko
#0  doadump (textdump=1) at pcpu.h:221
221     pcpu.h: No such file or directory.
        in pcpu.h
(kgdb) #0  doadump (textdump=1) at pcpu.h:221
#1  0xffffffff80a47b05 in kern_reboot (howto=<value optimized out>)
    at /mnt/sys/kern/kern_shutdown.c:366
#2  0xffffffff80a480db in vpanic (fmt=<value optimized out>, 
    ap=<value optimized out>) at /mnt/sys/kern/kern_shutdown.c:767
#3  0xffffffff80a48123 in panic (fmt=0x0) at /mnt/sys/kern/kern_shutdown.c:690
#4  0xffffffff80a51aa1 in mi_switch (flags=<value optimized out>, 
    newtd=<value optimized out>) at /mnt/sys/kern/kern_synch.c:389
#5  0xffffffff80a955e6 in sleepq_switch (wchan=<value optimized out>, pri=0)
    at /mnt/sys/kern/subr_sleepqueue.c:557
#6  0xffffffff80a954a3 in sleepq_wait (wchan=0xfffff80064622028, pri=0)
    at /mnt/sys/kern/subr_sleepqueue.c:637
#7  0xffffffff80a505a0 in _sx_xlock_hard (sx=<value optimized out>, 
    tid=<value optimized out>, opts=<value optimized out>, 
    file=<value optimized out>, line=<value optimized out>)
    at /mnt/sys/kern/kern_sx.c:701
#8  0xffffffff80a4fa3b in _sx_xlock (sx=0xfffff80064622028, opts=0, 
    file=0xffffffff830bbe91 "/mnt/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_lock.c", line=40) at sx.h:154
#9  0xffffffff830b361d in linux_mutex_lock_common (lock=0xfffff80064622028, 
    state=<value optimized out>, ctx=0xfffff8006493cc40)
    at /mnt/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_lock.c:40
#10 0xffffffff83061812 in modeset_lock (lock=0xfffff80064622028, 
    ctx=0xfffff8006493cc40, interruptible=false, slow=true) at ww_mutex.h:66
#11 0xffffffff83060d28 in drm_modeset_lock_all (dev=<value optimized out>)
    at /mnt/sys/modules/drm2/drm2/../../../dev/drm2/drm_modeset_lock.c:89
#12 0xffffffff830506d4 in drm_fb_helper_restore_fbdev_mode_unlocked (
    fb_helper=0xfffff800109d8600)
    at /mnt/sys/modules/drm2/drm2/../../../dev/drm2/drm_fb_helper.c:468
#13 0xffffffff83068e79 in vt_kms_postswitch (arg=0xfffff8000523ed00)
    at /mnt/sys/modules/drm2/drm2/../../../dev/drm2/linux_fb.c:76
#14 0xffffffff808d736b in vt_window_switch (vw=0xffffffff818d0290)
    at /mnt/sys/dev/vt/vt_core.c:540
#15 0xffffffff808d4e60 in vtterm_cngrab (tm=<value optimized out>)
    at /mnt/sys/dev/vt/vt_core.c:1465
#16 0xffffffff809ece32 in cngrab () at /mnt/sys/kern/kern_cons.c:368
#17 0xffffffff80a886c9 in kdb_trap (type=<value optimized out>, 
    code=<value optimized out>, tf=<value optimized out>)
    at /mnt/sys/kern/subr_kdb.c:651
#18 0xffffffff80eb73f1 in trap_fatal (frame=0xfffffe046282c510, eva=960)
    at /mnt/sys/amd64/amd64/trap.c:836
#19 0xffffffff80eb763d in trap_pfault (frame=0xfffffe046282c510, usermode=0)
    at /mnt/sys/amd64/amd64/trap.c:691
#20 0xffffffff80eb6b24 in trap (frame=0xfffffe046282c510)
    at /mnt/sys/amd64/amd64/trap.c:442
#21 0xffffffff80e97361 in calltrap () at /mnt/sys/amd64/amd64/exception.S:236
#22 0xffffffff82ea5ecb in pid_task (pid=881, type=PIDTYPE_PID) at pid.h:22
#23 0xffffffff82ea3120 in i915_gem_record_rings (dev=0xfffff8006460b000, 
    error=0xfffff80010661000)
    at /mnt/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_gpu_error.c:1043
#24 0xffffffff82ea1f43 in i915_capture_error_state (dev=0xfffff8006460b000, 
    wedged=true, error_msg=0xfffffe046282c7f0 "Ring hung")
    at /mnt/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_gpu_error.c:1346
#25 0xffffffff82eac3c5 in i915_handle_error (dev=0xfffff8006460b000, 
    wedged=true, fmt=0xffffffff82ff3240 "Ring hung")
    at /mnt/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_irq.c:2674
#26 0xffffffff82eafdcf in i915_hangcheck_elapsed (work=0xfffffe00079ae188)
    at /mnt/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_irq.c:3199
#27 0xffffffff830ade24 in linux_work_fn (context=0xfffffe00079ae188, 
    pending=<value optimized out>)
    at /mnt/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:1475
#28 0xffffffff80a99e4c in taskqueue_run_locked (queue=<value optimized out>)
    at /mnt/sys/kern/subr_taskqueue.c:463
#29 0xffffffff80a9a998 in taskqueue_thread_loop (arg=<value optimized out>)
    at /mnt/sys/kern/subr_taskqueue.c:717
#30 0xffffffff80a0a914 in fork_exit (
    callout=0xffffffff80a9a910 <taskqueue_thread_loop>, 
    arg=0xfffff8006400eb90, frame=0xfffffe046282cac0)
    at /mnt/sys/kern/kern_fork.c:1034
#31 0xffffffff80e9789e in fork_trampoline ()
    at /mnt/sys/amd64/amd64/exception.S:611
#32 0x0000000000000000 in ?? ()
Current language:  auto; currently minimal
(kgdb) 

```

**Comment by mattmacy** [comment]
Try again.

**Comment by nomadlogic** [comment]
ok this last check-in resets the GPU when it detects a hang.  it produces the following output in dmesg:

```
[drm] stuck on render ring
[drm] GPU HANG: ecode 7:0:0x87c3ffff, reason: Ring hung, action: reset
[drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
[drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
[drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
[drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
[drm] GPU crash dump saved to /sys/class/drm/card0/error
WARN_ON(domain->wake_count == 0)
drm/i915: Resetting chip after gpu hang
[drm] stuck on render ring
[drm] GPU HANG: ecode 7:0:0xf3cffffe, reason: Ring hung, action: reset
WARN_ON(domain->wake_count == 0)
drm/i915: Resetting chip after gpu hang
```

there are still artifacts in the display as well, although when i refresh the display manager in e16 everything works as expected.  in fact i'm able to watch video via youtube with minimal (if any) tearing and everything else seems responsive.  closing this guy out as we have other fish to fry.
