### ISSUE TITLE
kernel panic when exiting xfce4 using uxa acceleration on skylake

### ISSUE THREAD

**Issue by nomadlogic** [FreeBSDDesktop/freebsd-base-graphics#33]
uname: 3b2e17c(drm-next-4.6)-dirty
hw.model: Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz

here is the backtrace:

```
boomer dumped core - see /var/crash/vmcore.0

Thu Jun 16 19:32:33 PDT 2016

FreeBSD boomer 11.0-ALPHA1 FreeBSD 11.0-ALPHA1 #3 3b2e17c(drm-next-4.6)-dirty: Tue Jun 14 22:22:27 PDT 2016     root@srd0009:/usr/obj/usr/home/pwright/git/free
bsd-base-graphics/sys/GENERIC  amd64

panic: vm_page_assert_xbusied: page 0xfffff802681e9840 not exclusive busy @ /usr/home/pwright/git/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linux
kpi/common/src/linux_compat.c:698

GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...

Unread portion of the kernel message buffer:
vt_kms_postswitch() at vt_kms_postswitch+0x48/frame 0xfffffe02314342c0
vt_window_switch() at vt_window_switch+0xdb/frame 0xfffffe0231434300
vtterm_cngrab() at vtterm_cngrab+0x20/frame 0xfffffe0231434320
cngrab() at cngrab+0x32/frame 0xfffffe0231434340
vpanic() at vpanic+0x106/frame 0xfffffe02314343c0
kassert_panic() at kassert_panic+0x126/frame 0xfffffe0231434430
linux_cdev_pager_fault() at linux_cdev_pager_fault+0x5ee/frame 0xfffffe0231434560
dev_pager_getpages() at dev_pager_getpages+0x61/frame 0xfffffe02314345a0
vm_pager_get_pages() at vm_pager_get_pages+0x55/frame 0xfffffe02314345f0
vm_fault_hold() at vm_fault_hold+0x797/frame 0xfffffe0231434700
Dumping 683 out of 8040 MB:..3%..12%..22%..31%..43%..52%..61%..71%..82%..92%

<snip>

(kgdb) #0  doadump (textdump=0) at pcpu.h:221
#1  0xffffffff82d63e49 in vt_kms_postswitch (arg=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm2/drm2/../../../dev/drm2/linux_fb.c:82
#2  0xffffffff808d536b in vt_window_switch (vw=0xffffffff816ff750)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/dev/vt/vt_core.c:540
#3  0xffffffff808d2e60 in vtterm_cngrab (tm=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/dev/vt/vt_core.c:1465
#4  0xffffffff809eae32 in cngrab ()
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_cons.c:368
#5  0xffffffff80a46026 in vpanic (
    fmt=0xffffffff82dbb2fc "vm_page_assert_xbusied: page %p not exclusive busy @ %s:%d", ap=0xfffffe0231434400)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_shutdown.c:745
#6  0xffffffff80a45f16 in kassert_panic (fmt=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_shutdown.c:649
#7  0xffffffff82dae32e in linux_cdev_pager_fault (
    vm_obj=<value optimized out>, offset=0, prot=<value optimized out>, 
    mres=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:698
#8  0xffffffff80d178e1 in dev_pager_getpages (object=0xfffff8019d7ee210, 
    ma=0xfffffe0231434670, count=<value optimized out>, 
    rbehind=0xfffffe0231434668, rahead=0xfffffe023143466c, prot=0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/vm/device_pager.c:268
#9  0xffffffff80d40dc5 in vm_pager_get_pages (object=0xfffff8019d7ee210, 
    m=0xfffffe0231434670, count=1, rbehind=0x0, rahead=0x0, prot=0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/vm/vm_pager.c:291
#10 0xffffffff80d24807 in vm_fault_hold (map=0xfffff801476ef000, 
    vaddr=<value optimized out>, fault_type=2 '\002', fault_flags=0, 
    m_hold=0x0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/vm/vm_fault.c:652
#11 0xffffffff80d24028 in vm_fault (map=0xfffff801476ef000, 
    vaddr=<value optimized out>, fault_type=2 '\002', 
    fault_flags=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/vm/vm_fault.c:273
#12 0xffffffff80eb5555 in trap_pfault (frame=0xfffffe02314349c0, usermode=1)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/amd64/amd64/trap.c:741
#13 0xffffffff80eb4be2 in trap (frame=0xfffffe02314349c0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/amd64/amd64/trap.c:333
#14 0xffffffff80e95431 in calltrap ()
    at /usr/home/pwright/git/freebsd-base-graphics/sys/amd64/amd64/exception.S:236
#15 0x0000000801501ed6 in ?? ()
Previous frame inner to this frame (corrupt stack?)
Current language:  auto; currently minimal
(kgdb) 
```

**Comment by nomadlogic** [comment]
this is fixed as of:
3b2e17c(drm-next-4.6)-dirty
