### ISSUE TITLE
Kernel panic in __wake_up in linux/wait.h

### ISSUE THREAD

**Issue by dumbbell** [FreeBSDDesktop/freebsd-base-graphics#42]
I get the following panic pretty frequently on Haswell:

```
panic: uma_zfree_arg: called with spinlock or critical section held

#1  doadump (textdump=0)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_shutdown.c:298
#2  0xffffffff82670e19 in vt_kms_postswitch (arg=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/drm2/../../../dev/drm2/linux_fb.c:82
#3  0xffffffff808d774b in vt_window_switch (
    vw=0xffffffff81707860 <vt_conswindow>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/dev/vt/vt_core.c:540
#4  0xffffffff808d5240 in vtterm_cngrab (tm=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/dev/vt/vt_core.c:1465
#5  0xffffffff809ede92 in cngrab ()
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_cons.c:368
#6  0xffffffff80a491d6 in vpanic (
    fmt=0xffffffff813dd934 "uma_zfree_arg: called with spinlock or critical section held", ap=0xfffffe03d259c340)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_shutdown.c:745
#7  0xffffffff80a490c6 in kassert_panic (
    fmt=0xffffffff813dd934 "uma_zfree_arg: called with spinlock or critical section held")
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_shutdown.c:649
#8  0xffffffff80d246f3 in uma_zfree_arg (zone=0xfffff8001103e000, 
    item=0xfffff8005d165240, udata=0x0)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/vm/uma_core.c:2644
#9  0xffffffff80aafaea in uma_zfree (zone=<unavailable>, item=<unavailable>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/vm/uma.h:364
#10 doselwakeup (sip=<optimized out>, pri=-1)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/sys_generic.c:1837
#11 0xffffffff8265b9db in __wake_up (mode=1, q=<optimized out>, 
    nr=<optimized out>, key=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/drm2/../../../compat/linuxkpi/common/include/linux/wait.h:192
#12 drm_send_event_locked (dev=<optimized out>, e=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/drm2/../../../dev/drm2/drm_fops.c:814
#13 0xffffffff826606d6 in send_vblank_event (dev=0xfffff80032090000, 
    e=0xfffff801c167b900, seq=<optimized out>, now=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/drm2/../../../dev/drm2/drm_irq.c:1050
#14 drm_send_vblank_event (dev=0xfffff80032090000, pipe=0, 
    e=0xfffff801c167b900)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/drm2/../../../dev/drm2/drm_irq.c:1132
#15 0xffffffff824e756a in page_flip_completed (intel_crtc=0xfffff800320a5000)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/intel_display.c:3897
#16 0xffffffff824e6bda in do_intel_finish_page_flip (dev=0xfffff80032090000, 
    crtc=0xfffff800320a5000)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/intel_display.c:10896
#17 0xffffffff824e6c5c in intel_finish_page_flip_plane (
    dev=0xfffff80032090000, plane=0)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/intel_display.c:10914
#18 0xffffffff824b863b in ivb_display_irq_handler (dev=0xfffff80032090000, 
    de_iir=9)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_irq.c:2161
#19 0xffffffff824af473 in ironlake_irq_handler (irq=16, arg=0xfffff80032090000)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/i915/i915kms/../../../../dev/drm2/i915/i915_irq.c:2230
#20 0xffffffff826bf727 in linux_irq_handler (ent=0xfffff80011069e80)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:1590
#21 0xffffffff80a0e3dc in intr_event_handle (ie=<optimized out>, 
    frame=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_intr.c:1436
#22 0xffffffff80fad0f8 in intr_execute_handlers (isrc=0xfffff800056fb490, 
    frame=0xfffffe03d259c840)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/x86/x86/intr_machdep.c:275
#23 0xffffffff80fb1f18 in lapic_handle_intr (vector=61, 
    frame=0xfffffe03d259c840)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/x86/x86/local_apic.c:1143
#24 <signal handler called>
#25 0xffffffff803b423b in acpi_cpu_idle (sbt=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/dev/acpica/acpi_cpu.c:1216
#26 0xffffffff80faaadf in cpu_idle_acpi (sbt=22751746)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/x86/x86/cpu_machdep.c:263
#27 0xffffffff80faab85 in cpu_idle (busy=0)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/x86/x86/cpu_machdep.c:415
#28 0xffffffff80a760d5 in sched_idletd (dummy=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/sched_ule.c:2688
#29 0xffffffff80a0b974 in fork_exit (
    callout=0xffffffff80a75c30 <sched_idletd>, arg=0x0, 
    frame=0xfffffe03d259cac0)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_fork.c:1038
```

The kernel is at cd1bbc30.

**Comment by mattmacy** [comment]
This should be fixed by: https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/c132a998f8c9818f9c9e95fd2557f62f3ecd2fc7

**Comment by dumbbell** [comment]
The panic never occurred after a couple hours of Firefox/WebGL and Xonotic, where it took a few minutes to trigger with a simple terminal. So I confirm it's working now. Thank you!
