### ISSUE TITLE
panic: free: called with spinlock or critical section held

### ISSUE THREAD

**Issue by dumbbell** [FreeBSDDesktop/freebsd-base-graphics#57]
I just got the following panic with UXA when I exited X:

```
panic: free: called with spinlock or critical section held

#1  doadump (textdump=1)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_shutdown.c:298
#2  0xffffffff80a49b15 in kern_reboot (howto=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_shutdown.c:366
#3  0xffffffff80a4a0eb in vpanic (fmt=<optimized out>, ap=0xfffffe045612c440)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_shutdown.c:767
#4  0xffffffff80a49f26 in kassert_panic (
    fmt=0xffffffff8138af03 "free: called with spinlock or critical section held") at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_shutdown.c:649
#5  0xffffffff80a26b45 in free (addr=0xfffff8000ca07180, 
    mtp=0xffffffff826e97f0 <M_KMALLOC>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_malloc.c:543
#6  0xffffffff826646e5 in drm_events_release (file_priv=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/drm2/../../../dev/drm2/drm_fops.c:373
#7  drm_release (vnode=<optimized out>, filp=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/drm2/drm2/../../../dev/drm2/drm_fops.c:481
#8  0xffffffff826c6a41 in linux_file_dtor (cdp=0xfffff80159799900)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:559
#9  0xffffffff8091af9b in devfs_destroy_cdevpriv (p=0xfffff80013681b80)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/fs/devfs/devfs_vnops.c:193
#10 0xffffffff826c37f1 in linux_dev_close (dev=0xfffff8001387f600, 
    fflag=131079, devtype=8192, td=0xfffff80107fd8500)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:760
#11 0xffffffff8091db43 in devfs_close (ap=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/fs/devfs/devfs_vnops.c:648
#12 0xffffffff80fc164a in VOP_CLOSE_APV (vop=<optimized out>, 
    a=<optimized out>) at vnode_if.c:534
#13 0xffffffff80b1a8c7 in VOP_CLOSE (vp=0xfffff80159446938, fflag=7, 
    cred=0xfffff8000c83e900, td=0xfffff80107fd8500) at ./vnode_if.h:225
#14 vn_close (vp=0xfffff80159446938, flags=7, file_cred=0xfffff8000c83e900, 
    td=0xfffff80107fd8500)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/vfs_vnops.c:451
#15 0xffffffff80b195ca in vn_closefile (fp=0xfffff8001310e500, 
    td=0xfffff80107fd8500)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/vfs_vnops.c:1579
#16 0xffffffff8091e6ec in devfs_close_f (fp=0xfffff8001310e500, 
    td=<unavailable>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/fs/devfs/devfs_vnops.c:667
#17 0xffffffff809f643a in fo_close (fp=0xfffff8001310e500, td=<unavailable>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/sys/file.h:351
#18 _fdrop (fp=0xfffff8001310e500, td=<unavailable>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_descrip.c:2829
#19 0xffffffff809f9560 in closef (fp=<optimized out>, td=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_descrip.c:2430
#20 0xffffffff809f904d in fdescfree_fds (td=0xfffff80107fd8500, 
    fdp=<optimized out>, needclose=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_descrip.c:2140
#21 0xffffffff809f8bdf in fdescfree (td=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_descrip.c:2203
#22 0xffffffff80a07859 in exit1 (td=<optimized out>, rval=<optimized out>, 
    signo=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_exit.c:375
#23 0xffffffff80a0736d in sys_sys_exit (td=<unavailable>, uap=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/kern/kern_exit.c:178
#24 0xffffffff80ebcb2b in syscallenter (td=0xfffff80107fd8500, 
    sa=<optimized out>)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/amd64/amd64/../../kern/subr_syscall.c:135
#25 amd64_syscall (td=0xfffff80107fd8500, traced=0)
    at /mnt/home/dumbbell/Projects/freebsd/src/GIT/sys/amd64/amd64/trap.c:942
#26 <signal handler called>
#27 0x000000080225ce1a in ?? ()
```

This is with drm-next-4.6 de6f1ed.

**Comment by mattmacy** [comment]
Please retry with latest.

**Comment by dumbbell** [comment]
I didn't hit this panic for a long time, so I consider it fixed.

Thanks!
