### ISSUE TITLE
panic on c464d4d

### ISSUE THREAD

**Issue by nomadlogic** [FreeBSDDesktop/freebsd-base-graphics#70]
i've had a random panic on c464d4d.  i was able to capture core and a trace.  here's the error:

```
panic: mi_switch: switch in a critical section
<snip>
Unread portion of the kernel message buffer:
vt_kms_postswitch() at vt_kms_postswitch+0x48/frame 0xfffffe02326d7d60
vt_window_switch() at vt_window_switch+0xdb/frame 0xfffffe02326d7da0
vtterm_cngrab() at vtterm_cngrab+0x20/frame 0xfffffe02326d7dc0
cngrab() at cngrab+0x32/frame 0xfffffe02326d7de0
vpanic() at vpanic+0x106/frame 0xfffffe02326d7e60
kassert_panic() at kassert_panic+0x126/frame 0xfffffe02326d7ed0
mi_switch() at mi_switch+0x1b5/frame 0xfffffe02326d7f00
turnstile_wait() at turnstile_wait+0x3be/frame 0xfffffe02326d7f50
__mtx_lock_sleep() at __mtx_lock_sleep+0x18c/frame 0xfffffe02326d7fd0
__lkpi_mtx_lock_flags() at __lkpi_mtx_lock_flags+0xd6/frame 0xfffffe02326d8020
```

and the full backtrace here:

```

#0  doadump (textdump=0) at pcpu.h:221
221     pcpu.h: No such file or directory.
        in pcpu.h
(kgdb) #0  doadump (textdump=0) at pcpu.h:221
#1  0xffffffff82ded3e9 in vt_kms_postswitch (arg=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/drm/../../../dev/drm/linux_fb.c:82
#2  0xffffffff808dea8b in vt_window_switch (vw=0xffffffff8171ee60)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/dev/vt/vt_core.c:540
#3  0xffffffff808dc550 in vtterm_cngrab (tm=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/dev/vt/vt_core.c:1465
#4  0xffffffff809f5fe2 in cngrab ()
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_cons.c:368
#5  0xffffffff80a50126 in vpanic (
    fmt=0xffffffff813a3609 "mi_switch: switch in a critical section", 
    ap=0xfffffe02326d7ea0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_shutdown.c:745
#6  0xffffffff80a50016 in kassert_panic (fmt=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_shutdown.c:649
#7  0xffffffff80a59f55 in mi_switch (flags=259, newtd=0x0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_synch.c:408
#8  0xffffffff80aa778e in turnstile_wait (ts=<value optimized out>, 
    owner=<value optimized out>, queue=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/subr_turnstile.c:751
#9  0xffffffff80a315ac in __mtx_lock_sleep (c=<value optimized out>, 
    tid=18446735277819394592, opts=<value optimized out>, 
    file=<value optimized out>, line=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_mutex.c:602
#10 0xffffffff82c25746 in __lkpi_mtx_lock_flags (c=0xfffffe0007924a40, 
    opts=0, 
    file=0xffffffff82d84b52 "/usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../compat/linuxkpi/common/include/linux/spinlock.h", line=127)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/lkpi_kern_mutex.c:148
#11 0xffffffff82d16e64 in intel_logical_ring_advance_and_submit ()
    at spinlock.h:127
#12 0xffffffff82d16c64 in gen8_emit_request_render (
    request=0xfffff800ac03e600)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../dev/drm/i915/intel_lrc.c:1867
#13 0xffffffff82c910d7 in __i915_add_request (request=0xfffff800ac03e600, 
    obj=<value optimized out>, flush_caches=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../dev/drm/i915/i915_gem.c:2995
#14 0xffffffff82c9c8ea in i915_gem_do_execbuffer ()
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../dev/drm/i915/i915_gem_execbuffer.c:1143
#15 0xffffffff82c9cae5 in i915_gem_execbuffer2 (dev=0xfffffe0007922000, 
    data=0xfffffe02326d84c0, linux_file=0xfffff800ac63e000)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../dev/drm/i915/i915_gem_execbuffer.c:1800
#16 0xffffffff82ddb3be in drm_ioctl (filp=<value optimized out>, 
    cmd=<value optimized out>, arg=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/drm/../../../dev/drm/drm_ioctl.c:721
#17 0xffffffff82c14f3a in linux_dev_ioctl (dev=<value optimized out>, 
    cmd=2151703657, data=0x0, fflag=<value optimized out>, td=0x0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:921
#18 0xffffffff80924b33 in devfs_ioctl (ap=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/fs/devfs/devfs_vnops.c:831
#19 0xffffffff80fd3700 in VOP_IOCTL_APV (vop=<value optimized out>, 
    a=<value optimized out>) at vnode_if.c:1067
#20 0xffffffff80b2061c in vn_ioctl (fp=0xfffff8000c467910, 
    com=<value optimized out>, data=0xfffffe02326d87f0, 
    active_cred=0xfffff80008975700, td=0x0) at vnode_if.h:448
#21 0xffffffff8092524f in devfs_ioctl_f (fp=0x0, com=0, data=0x0, cred=0x0, 
    td=0xfffff8000c177a20)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/fs/devfs/devfs_vnops.c:789
#22 0xffffffff80ab5fc6 in kern_ioctl (td=<value optimized out>, 
    fd=<value optimized out>, com=<value optimized out>, 
    data=<value optimized out>) at file.h:328
#23 0xffffffff80ab5d11 in sys_ioctl (td=<value optimized out>, 
    uap=0xfffffe02326d8940)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/sys_generic.c:748
#24 0xffffffff80ec6b6b in amd64_syscall (td=0xfffff8000c177a20, traced=0)
    at subr_syscall.c:135
#25 0xffffffff80ea631b in Xfast_syscall ()
    at /usr/home/pwright/git/freebsd-base-graphics/sys/amd64/amd64/exception.S:396
#26 0x000000080250474a in ?? ()
Previous frame inner to this frame (corrupt stack?)
Current language:  auto; currently minimal
(kgdb) 

```

**Comment by mattmacy** [comment]
Thanks. Will fix ASAP.

**Comment by mattmacy** [comment]
I've added an assert to lock acquisition. This path being executed means that the lockholder has been preempted -- which should never happen.

**Comment by mattmacy** [comment]
try https://github.com/FreeBSDDesktop/freebsd-base-graphics/commit/d8febfcaec8ee2eb111e6e5c403d265132508af8

This isn't a proper fix but should reduce the chance of user space preempting the thread running the tasklet until I have time to write a complete fix.

**Comment by nomadlogic** [comment]
OK I'll update my system today.  I did get another panic while I left my workstation idle over night.  Capture core - here's the info for posterity:

```
panic: mi_switch: switch in a critical section

GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...

Unread portion of the kernel message buffer:
vt_kms_postswitch() at vt_kms_postswitch+0x48/frame 0xfffffe02322d7d60
vt_window_switch() at vt_window_switch+0xdb/frame 0xfffffe02322d7da0
vtterm_cngrab() at vtterm_cngrab+0x20/frame 0xfffffe02322d7dc0
cngrab() at cngrab+0x32/frame 0xfffffe02322d7de0
vpanic() at vpanic+0x106/frame 0xfffffe02322d7e60
kassert_panic() at kassert_panic+0x126/frame 0xfffffe02322d7ed0
mi_switch() at mi_switch+0x1b5/frame 0xfffffe02322d7f00
turnstile_wait() at turnstile_wait+0x3be/frame 0xfffffe02322d7f50
__mtx_lock_sleep() at __mtx_lock_sleep+0x18c/frame 0xfffffe02322d7fd0
__lkpi_mtx_lock_flags() at __lkpi_mtx_lock_flags+0x102/frame 0xfffffe02322d8020
Dumping 3043 out of 8047 MB:..1%..11%..21%..31%..41%..51%..61%..71%..81%..91%
<snip>
(kgdb) #0  doadump (textdump=0) at pcpu.h:221
#1  0xffffffff82ded3e9 in vt_kms_postswitch (arg=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/drm/../../../dev/drm/linux_fb.c:82
#2  0xffffffff808dea8b in vt_window_switch (vw=0xffffffff8171ee60)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/dev/vt/vt_core.c:540
#3  0xffffffff808dc550 in vtterm_cngrab (tm=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/dev/vt/vt_core.c:1465
#4  0xffffffff809f5fe2 in cngrab ()
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_cons.c:368
#5  0xffffffff80a50126 in vpanic (
    fmt=0xffffffff813a3609 "mi_switch: switch in a critical section", 
    ap=0xfffffe02322d7ea0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_shutdown.c:745
#6  0xffffffff80a50016 in kassert_panic (fmt=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_shutdown.c:649
#7  0xffffffff80a59f55 in mi_switch (flags=259, newtd=0x0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_synch.c:408
#8  0xffffffff80aa778e in turnstile_wait (ts=<value optimized out>, 
    owner=<value optimized out>, queue=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/subr_turnstile.c:751
#9  0xffffffff80a315ac in __mtx_lock_sleep (c=<value optimized out>, 
    tid=18446735277825352976, opts=<value optimized out>, 
    file=<value optimized out>, line=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/kern_mutex.c:602
#10 0xffffffff82c25772 in __lkpi_mtx_lock_flags (c=0xfffffe0007be0a40, 
    opts=0, 
    file=0xffffffff82d84b52 "/usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../compat/linuxkpi/common/include/linux/spinlock.h", line=127)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/lkpi_kern_mutex.c:153
#11 0xffffffff82d16e64 in intel_logical_ring_advance_and_submit ()
    at spinlock.h:127
#12 0xffffffff82d16c64 in gen8_emit_request_render (
    request=0xfffff801385fd500)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../dev/drm/i915/intel_lrc.c:1867
#13 0xffffffff82c910d7 in __i915_add_request (request=0xfffff801385fd500, 
    obj=<value optimized out>, flush_caches=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../dev/drm/i915/i915_gem.c:2995
#14 0xffffffff82c9c8ea in i915_gem_do_execbuffer ()
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../dev/drm/i915/i915_gem_execbuffer.c:1143
#15 0xffffffff82c9cae5 in i915_gem_execbuffer2 (dev=0xfffffe0007bde000, 
    data=0xfffffe02322d84c0, linux_file=0xfffff80081a38400)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/i915/i915kms/../../../../dev/drm/i915/i915_gem_execbuffer.c:1800
#16 0xffffffff82ddb3be in drm_ioctl (filp=<value optimized out>, 
    cmd=<value optimized out>, arg=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/drm/drm/../../../dev/drm/drm_ioctl.c:721
#17 0xffffffff82c14f3a in linux_dev_ioctl (dev=<value optimized out>, 
    cmd=2151703657, data=0x0, fflag=<value optimized out>, td=0x0)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/modules/linuxkpi/../../compat/linuxkpi/common/src/linux_compat.c:921
#18 0xffffffff80924b33 in devfs_ioctl (ap=<value optimized out>)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/fs/devfs/devfs_vnops.c:831
#19 0xffffffff80fd3700 in VOP_IOCTL_APV (vop=<value optimized out>, 
    a=<value optimized out>) at vnode_if.c:1067
#20 0xffffffff80b2061c in vn_ioctl (fp=0xfffff8000c4444b0, 
    com=<value optimized out>, data=0xfffffe02322d87f0, 
    active_cred=0xfffff8000c78f400, td=0x0) at vnode_if.h:448
#21 0xffffffff8092524f in devfs_ioctl_f (fp=0x0, com=0, data=0x0, cred=0x0, 
    td=0xfffff8000c726510)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/fs/devfs/devfs_vnops.c:789
#22 0xffffffff80ab5fc6 in kern_ioctl (td=<value optimized out>, 
    fd=<value optimized out>, com=<value optimized out>, 
    data=<value optimized out>) at file.h:328
#23 0xffffffff80ab5d11 in sys_ioctl (td=<value optimized out>, 
    uap=0xfffffe02322d8940)
    at /usr/home/pwright/git/freebsd-base-graphics/sys/kern/sys_generic.c:748
#24 0xffffffff80ec6b6b in amd64_syscall (td=0xfffff8000c726510, traced=0)
    at subr_syscall.c:135
#25 0xffffffff80ea631b in Xfast_syscall ()
    at /usr/home/pwright/git/freebsd-base-graphics/sys/amd64/amd64/exception.S:396
#26 0x000000080250474a in ?? ()
Previous frame inner to this frame (corrupt stack?)
Current language:  auto; currently minimal
(kgdb) 
```

**Comment by nomadlogic** [comment]
system has been stable for day-to-day use on 3bb585c for over 48hours so i'm closing this guy out.
