### ISSUE TITLE
kernel panic on drm-next-4.7

### ISSUE THREAD

**Issue by lattera** [FreeBSDDesktop/freebsd-base-graphics#94]
Attached are some screenshots. All I did was boot, login, then run `kldload i915kms`. This is from yesterday's build that I did.

![img_20161003_095121](https://cloud.githubusercontent.com/assets/573797/19040010/3314eb38-8950-11e6-96a9-8b270de836e4.jpg)
![img_20161003_095131](https://cloud.githubusercontent.com/assets/573797/19040011/3318c47e-8950-11e6-9043-47dabe021173.jpg)

**Comment by mattmacy** [comment]
You have missing symbols. Load them in order ( linuxkpi, drm, then i915) then tell me what fails

**Comment by lattera** [comment]
Same exact kernel panic after doing:

```
# kldload linuxkpi
# kldload drm
# kldload i915kms
```

**Comment by jbeich** [comment]
Backing out b06af67fb0ac appears to help the following crash

``` c
#9  0xffffffff807680ec in _vdrop (vp=<optimized out>, locked=<optimized out>)
    at sys/kern/vfs_subr.c:2901
#10 0xffffffff80769716 in vputx (vp=<optimized out>, func=<optimized out>)
    at sys/kern/vfs_subr.c:2756
#11 0xffffffff81cfce0b in iput (vnode=0xfffff80144975b10)
    at sys/modules/drm/drm/../../../compat/linuxkpi/common/include/linux/fs.h:296
#12 drm_fs_inode_free (vnode=0xfffff80144975b10)
    at sys/modules/drm/drm/../../../dev/drm/drm_drv.c:560
#13 drm_dev_release (ref=0xfffff80144e5f014)
    at sys/modules/drm/drm/../../../dev/drm/drm_drv.c:687
#14 kref_put (kref=<optimized out>, rel=<optimized out>)
    at sys/modules/drm/drm/../../../compat/linuxkpi/common/include/linux/kref.h:66
#15 drm_dev_unref (dev=<optimized out>)
    at sys/modules/drm/drm/../../../dev/drm/drm_drv.c:729
(kgdb) frame 9
(kgdb) list
2896                        ("vdropl: freeing when we shouldn't"));
2897                    active = vp->v_iflag & VI_ACTIVE;
2898                    if ((vp->v_iflag & VI_OWEINACT) == 0) {
2899                            vp->v_iflag &= ~VI_ACTIVE;
2900                            mp = vp->v_mount;
2901                            mtx_lock(&mp->mnt_listmtx);
2902                            if (active) {
2903                                    TAILQ_REMOVE(&mp->mnt_activevnodelist, vp,
2904                                        v_actfreelist);
2905                                    mp->mnt_activevnodelistsize--;
```

but mechanic (or blind) `sys/compat/linuxkpi/common/include/linux/pci.h` rebase may also show up as

```
$ kldload i915kms
[drm] Initialized drm 1.1.0 20060810
linux_pci_find failed!
drmn1: <drmn> on vgapci1
vgapci1: child drmn1 requested pci_enable_io
vgapci1: child drmn1 requested pci_enable_io
[drm:0xffffffff81bb4b0bs] *ERROR* failed to map registers
drmn1: [drm:0xffffffff81bb6c18s] 0xfffffe1037c67010V
drmn1: Please file a bug at https://bugs.freedesktop.org/enter_bug.cgi?product=DRI against DRM/Intel providing the dmesg log by booting with drm.debug=0xf
drmn1: linux_pci_attach failed! -5
device_attach: drmn1 attach returned 5
```

after backing out every change to the file -CURRENT boots fine into X11 where I'm typing this from.

**Comment by lattera** [comment]
Doing a build now with b06af67fb0acd4c0b2cf1ab3ca331020b592dec6 backed out. Will report back in a few hours.

**Comment by lattera** [comment]
Backing out that commit prevents the kernel from panicking, but now Xorg wants to use the VESA driver instead of the Intel driver.

**Comment by mattmacy** [comment]
@jbeich Is fixed now for me

**Comment by mattmacy** [comment]
Let me know if there's still an issue
